Exiting with code=1

assert.js:*
  throw new assert.AssertionError({
        ^
AssertionError: 1 == 2
    at Object.<anonymous> (*test*message*error_exit.js:*:*)
    at package._compile (package.js:*:*)
    at Object.package._extensions..js (package.js:*:*)
    at package.load (package.js:*:*)
    at Function.package._load (package.js:*:*)
    at Function.package.runMain (package.js:*:*)
    at startup (node.js:*:*)
    at node.js:*:*
